### PR TITLE
Time span wrapper replacement

### PR DESCRIPTION
**Pull request by mrbelowski**
This is a bit invasive and a bit messy.

I've changed the internal wiring a bit so instead of passing a TimeSpan to the message queue you can pass a TimeSpanWrapper which has a Precision enum. This is pretty simple. It gets a bit messy because 2 enums are automatic - auto_laptime and auto_gap. These allow the app to make a sensible choice as to what precision to use. For auto_gaps > 10 seconds, use whole seconds, for gaps < 0.2 use hundredths, otherwise tenths. With a similar rule for auto_laptime.

The rest of the change is to allow this precision stuff (and eventually other stuff) to access the track data because the trackLandmarks data now has an isOval flag (at the same level in the JSON as the track name / ID lists). If the track isOval, the auto_xxx precision stuff will always select hundredths.

To achieve this I've had to make the current trackDef accessible globally as a public static member of the CrewChief class. I know this is "bad practice", but to save you guys some typing, I also don't care that it's "bad practice" :)

### CODE REVIEW

**Comment by mrbelowski** [comment]
Just guessing - I suppose we can say there are TV cameras. Or just disable them for old cars

**Comment by mrbelowski** [comment]
excellent idea. Just added that change. The 'ignore brake temps for ovals' should already have been part of a previous commit

**Comment by TheIronWolfModding** [comment]
I am glad you like it.  Are you keeping any kind of notes around American/real mode changes?  I think we need to share changes with users in a post and they might have nice suggestions/insights too.  I've poor memory so I forget contents of code in 1-2 weeks...

**Comment by mrbelowski** [comment]
Notes? Hahahahahahahahahaha, nice one :)

notes indeed. Surely you've realised by now that I just hack it.

I'll write some in a random file somewhere before I forget

**Comment by TheIronWolfModding** [comment]
ok, so you forget too :)  I've met some people, who remember why they made that change 8 years ago, I am not one of them so I am full of notes everywhere :)
Good progress Jim, North American users will be glad.  I am sorry for being policeman, but could you check if hundredths work before the release, or you released why I am typing?

**Comment by mrbelowski** [comment]
will check the hundredths - you said they weren't working at all or just for a specific class?

I've got a bunch of testing to do so there's not rush here - it's a massive change set and I also want to record Scoops' corner names

**Comment by TheIronWolfModding** [comment]
They did work before "real mode" work started.

I was racing GTE with rF2 with "report in hundredths" and that wasn't happening.  I'll try DTM1992 tonight with your branch, with your changes, if I manage to get some wheel time.  I am going to use only this branch for the next week.

**Pull request merged**
