### PR TITLE
Assetto Corsa 1.12

### PR DESCRIPTION
**Pull request by Sparten**
added a few more cars to carclasses, and a few other fixes.

### CODE REVIEW

**Comment by Sparten** [comment]
I can close this again incase you want to wait untill next update ?

**Comment by mrbelowski** [comment]
no, let's put it in. Any reason why those control input mappings were removed? Just cos they aren't used anywhere? Or is the data no good? I don't think we use them for anything with Assetto, but we might find a use for them

**Comment by mrbelowski** [comment]
ah, ignore me, i see it's mapped twice :)

**Comment by Sparten** [comment]
was just about to say.

**Comment by mrbelowski** [comment]
is there anything else you'd like in the next release for Assetto?

**Comment by Sparten** [comment]
No i think this is it ofr now.

**Comment by mrbelowski** [comment]
good stuff. I won't package it until just before I release it (Tuesday evening i think) so there's still time to add changes if we need to

**Pull request merged**
