### PR TITLE
Car Classes data: allow brake, tyre temp, and spotter length/widht overrides.  Main App: minimize unneeded exceptions on file open.  Rf2: small fixes

### PR DESCRIPTION
**Pull request by TheIronWolfModding**

### CODE REVIEW

**Comment by TheIronWolfModding** [comment]
Your suggestion makes sense, I'll fix it.  Is there any problem of having currentGameState made accessible to Spotters (and what's the best way to achieve that?)  Then, I'll cache classId string, but getting player car class will become even easier.

**Comment by mrbelowski** [comment]
It's currently a member variable of the CrewChief class, but I think it would be safe to make it public and static. Do we really need this though? If the spotter class has a String carClassId member var (Integer for R3E) then we just get the byte[] from the game-specific currentStateObj Struct, turn it into a String and compare it to the class member and if it doesn't match, retrieve and set the car dimensions?

**Comment by mrbelowski** [comment]
Actually, maybe we *should* just make the currentGameState visible to the spotter. It's in another Thread but this should be ok

**Comment by TheIronWolfModding** [comment]
If it's on another thread, won't we need locking?  This might end up hairy change for the task at hand.  I think for now I'll do simple caching and will revisit as I learn more about CC and threads in there.

**Comment by mrbelowski** [comment]
I don't think we'll need to lock here because the spotter Thread never changes it. It may be null but the carClass property of the GameStateData is a single thing, its assignment is atomic and we don't need any other data from the main Thread's currentGameState

**Comment by TheIronWolfModding** [comment]
Ok, I will take local references to things before checking their values, so that is currentGameState is nulled out somewhere, Spotter is not affected.

**Pull request merged**
