### PR TITLE
Assettocorsa

### PR DESCRIPTION
**Pull request by Sparten**
Latest update.
There is a small issue when going to pause where it wants to restart session, if the session is timed.
Also CrewChiefV4.sln had its VS version changed, but that should not be an issue.(I tryed to revert but it didnt work out)

### CODE REVIEW

**Comment by mrbelowski** [comment]
Looks fine but can you delete that commented out code block from crewchief.cs is you don't need it any more

**Comment by Sparten** [comment]
Sure will do so, but you will get a few more updates to gamestatemapper.

**Comment by Sparten** [comment]
Do i need to make another pull request, for you to get the latest commit ?

**Comment by mrbelowski** [comment]
Don't think so - the pull request now contains a commit you made (7e221aa7da95584261c964a086020a48428d04e6) which includes a bunch of additions to the AC gamestate mapper - a chunk of logic triggered on IsNewSector

**Pull request merged**
