### PR TITLE
Assetto Corsa

### PR DESCRIPTION
**Pull request by Sparten**

### CODE REVIEW

**Comment by Sparten** [comment]
Ive adde the latest ACSGameStateMapper aswell, you can just reject it if you do not approve of the idea.
If you decide to include I'll write a small howto on sector loggin.

Ive started on adding tyres for assetto corsa, ive still got alot of them still to go.

**Comment by Sparten** [comment]
I wrote this so you do not need to wait for my slow typing if you decide to include. 

How to log sectors for unknown tracks in Assetto Corsa:
-Go to Properties and enable "enable_acs_log_sectors_for_unknown_tracks". 
-Click Save and Restart.
-Now select the the track you want to log sectors for and drive slow 1 lap around the track.
-Now in the console window of CrewChifeV4 you will find a line looking like this:
"new TrackDefinition("paul_ricard:gt_24h", 5776.583f, 3, new float[] {2971.514f, 4184.762f})"
But with different trackname and values.

-Send the logged line to: sportcorp@hotmail.com with the track name as subject.
-Or make a post here: http://www.assettocorsa.net/forum/index.php?threads/crew-chief-for-assetto-corsa.36440/  

NB.New tracks will only be added when/if a new release of CrewChiefV4 is planned.

**Comment by mrbelowski** [comment]
The changes look fine so I'll merge now. I think the request for users to collect track data is a good idea, but I think it'll be easier to add this to the forum thread rather than the readme at this point

**Comment by Sparten** [comment]
Ok not a problem.

**Pull request merged**
