### PR TITLE
Assetto Corsa

### PR DESCRIPTION
**Pull request by Sparten**
Hope this will work says that cant automatically merge. but i cant see what the issue is.

### CODE REVIEW

**Comment by mrbelowski** [comment]
It's probably something trivial like line ending characters. It'll have to wait until this evening but I'll give you a yell if there's an actual problem - I'll merge it (if I can) and start preparing for a release

**Comment by Sparten** [comment]
Have to close it says i cant pull changes from it so i'll have to rever and then recommit i maby did something stupid and made a change directly on github.

**Comment by Sparten** [comment]
Should be ok on my end now, i think i made a mistake by not pulling from yours before i comitted last time.

**Comment by mrbelowski** [comment]
I think this PR might need to be re-made - it's still conflicting. I can take a look at the conflicts at my end later, if you're happy to wait :)

**Comment by Sparten** [comment]
Thats ok with me, sry for late reply was getting attaked by a sofa.

**Comment by mrbelowski** [comment]
manually merged changes

**Pull request closed without merging**
