### PR TITLE
Assetto Corsa

### PR DESCRIPTION
**Pull request by Sparten**
You should be able to release an update with this, there is not much more i want to do with the python code for now, and from what i can see ive got the data exported that i need to be able to continue with the rest that needs or can be added.

### CODE REVIEW

**Comment by mrbelowski** [comment]
Looking at the ASCData class, I see that the opponent world position data is in the SPageFileCrewChief struct. This is what gets created by your Python code. I *think* all the data the spotter needs is in this struct so...

ASCSharedMemoryReader.ReadGameData(Boolean forSpotter)

only has to read one of the shared memory objects if forSpotter is true. Or, more simply, always populate the SPageFileCrewChief but only populate the other 3 struts if forSpotter is false. The spotter has its own Thread which calls ReadGameData every 10ms, but the main game Thread calls ReadGameData every 100ms. So by doing this you save a lot of unnecessary shared memory object access and processing

**Comment by Sparten** [comment]
I Will do that right away.

**Comment by Sparten** [comment]
Fixed! Makes real good sense not to process that every iteration

**Comment by Sparten** [comment]
There is something i need to change in the spotter code as it also uses data from SPageFileGraphic but that is also availeble in SPageFileCrewChief so i will chang now.

**Comment by Sparten** [comment]
Thats is as much as i can do the i need SPageFilePhysics for yaw :( but i hope it still helps a little bit.

**Comment by mrbelowski** [comment]
good spot on the orientation data :)

merging now, will cut a release tonight if I find the time

**Pull request merged**
