### PR TITLE
Assetto Corsa 1.12

### PR DESCRIPTION
**Pull request by Sparten**
Opponent race finished check. (same as in R3E)

### CODE REVIEW

**Comment by Sparten** [comment]
Dont we need to copy SessionData.HasExtraLap from previousGameState to currentGameState in "if (!justGoneGreen && previousGameState != null)" Block ?

**Comment by mrbelowski** [comment]
Yra

**Comment by mrbelowski** [comment]
Argghh, fcking mobile phone, what have I done? All I wanted to do was say "yes"

**Comment by Sparten** [comment]
ok i'll push that change.

**Comment by Sparten** [comment]
added it!

**Pull request merged**
