### PR TITLE
rF2/rF1: only praise user on clean passes.

### PR DESCRIPTION
**Pull request by TheIronWolfModding**
Kinda tested on traces :)

### CODE REVIEW

**Comment by TheIronWolfModding** [comment]
Crap, how to unselect you from required reviewers :D

**Comment by TheIronWolfModding** [comment]
employ of the month !!!!!

**Comment by mrbelowski** [comment]
Aww man, right above this comment box it says "You're all set - the rf2 branch can be safely deleted" with a big "Delete branch" button

Must.... not.... press.... button


arrrgghhh

the mouse keeps drifting over to the button


Noooooooooooo my finger is twitching. Now it says "Press me"

**Comment by TheIronWolfModding** [comment]
:))))) oh man, yeah maybe all of this is an overkill for our small application really.

**Comment by TheIronWolfModding** [comment]
nah Jim, thanks for keeping it fun.  But America made me obsessed with efficiency, and I am torn between going all cowboy, and doing all in master, and full blown corp style.   Anyway, I think we're doing fine.

**Pull request merged**
